# path_df: ../data/roman_c1.csv
path_df: ../data/roman_ETHUSD_c1_d16-28.csv
trading_step: 200
window_step: 40
train_start_idx: 1
train_end_idx: 905000
test_start_idx: 910000
test_end_idx: end
commission: -0.0002

eps_start:     0.80
eps_end:       0.005
eps_decay:     40000
noise_sigma:   15.0
noise_mean:    25.0
reward_decay:  0.7
lr:            1e-9
reg_vol:       2.0
reg_action:    1e-6
rew_offset:    5.0
warm_up_episodes: 50
alpha:         0.9
gamma:         0.5
t_beta:        0.4
lr_decay:      0.9997
gradient_clip: 1e-8
A_layers: 
    - 1024
    - 256
    - 16
C_layers: 
    - 128
    - 15

episodes: 6000
eval_every: 50
max_episode_len: 10
replay_memory_len: 2048
replay_batch: 64

exclude_cols:
    - "target"
    - "target_min"
    - "target_max" 
    - "midprice_vwap_v220000.0"
    - "vwap_midprice_diff_v220000.0"
    - "midprice_vwap_v130000.0"
    - "vwap_midprice_diff_v130000.0"
    - "log_vwap_midprice_ratio_v220000.0"
    - "nlrr_ws100"
    - "nlrr_ws500" 
    - "mean_trend_ws100_midprice"
    - "std_trend_ws100_midprice"
    - "vol_ws100_midprice"
    - "mean_trend_ws500_midprice"
    - "std_trend_ws500_midprice"
    - "vol_ws500_midprice"
    - "mean_trend_ws100_midprice_vwap_v130000.0"
    - "std_trend_ws100_midprice_vwap_v130000.0"
    - "vol_ws100_midprice_vwap_v130000.0"
    - "mean_trend_ws500_midprice_vwap_v130000.0"
    - "std_trend_ws500_midprice_vwap_v130000.0"
    - "vol_ws500_midprice_vwap_v130000.0"
    - "mean_trend_ws100_midprice_vwap_v220000.0"
    - "std_trend_ws100_midprice_vwap_v220000.0"
    - "vol_ws100_midprice_vwap_v220000.0"
    - "mean_trend_ws500_midprice_vwap_v220000.0"
    - "std_trend_ws500_midprice_vwap_v220000.0"
    - "vol_ws500_midprice_vwap_v220000.0"
    - "new_trend_value_ws100_midprice"
    - "new_trend_value_ws100_midprice_vwap_v130000.0"
    - "new_trend_value_ws100_midprice_vwap_v220000.0"
    - "new_trend_value_ws500_midprice"
    - "new_trend_value_ws500_midprice_vwap_v130000.0"
    - "new_trend_value_ws500_midprice_vwap_v220000.0"
    - "mean_trend_ws2500_midprice_vwap_v130000.0"
    - "mean_trend_ws2500_midprice_vwap_v220000.0"
    - "std_trend_ws2500_midprice_vwap_v220000.0"
    - "vol_ws2500_midprice_vwap_v220000.0"



