#--------------general settings-----------------
path_df: ../data/roman_ETHUSD_c1_d16-28.csv
train_start_idx: 1
train_end_idx: 905000
test_start_idx: 910000
test_end_idx: end

#--------------model settings-----------------
A_layers: 
    - 256
    - 16
C_layers: 
    - 512
    - 16

#--------------training settings-----------------
#---episodes and replay buffer
episodes: 4000
eval_every: 100
max_episode_len: 10
replay_memory_len: 512
replay_batch: 64
#---EvE variables
eps_start:     0.90
eps_end:       0.05
eps_decay:     7000
noise_sigma:   0.1
noise_mean:    0.0
#---reward variables
reg_vol:       50.0
reg_action:    1e-2
rew_offset:    5.0
warm_up_episodes: 50
reward_decay:  0.2
#--- Q calculation: Qp + alpha * (R + gamma * Qt' - Qp)
alpha:         0.9
gamma:         0.5
#---learning rate
lr_A:          1e-2
lr_C:          1e-6
lr_decay_A:    0.995
lr_decay_C:    0.993
gradient_clip: 1e-1
#---target update settings
t_beta:        0.2

#--------------env settings-----------------
trading_step: 200
window_step: 20
commission: -0.0002
exclude_cols:
    # - "target"
    # - "target_min"
    # - "target_max" 
    - "midprice_vwap_v220000.0"
    - "vwap_midprice_diff_v220000.0"
    - "midprice_vwap_v130000.0"
    - "vwap_midprice_diff_v130000.0"
    - "log_vwap_midprice_ratio_v220000.0"
    - "nlrr_ws100"
    - "nlrr_ws500" 
    - "nlrr_ws2500" 
    - "mean_trend_ws100_midprice"
    - "std_trend_ws100_midprice"
    - "vol_ws100_midprice"
    - "mean_trend_ws500_midprice"
    - "std_trend_ws500_midprice"
    - "vol_ws500_midprice"
    - "mean_trend_ws100_midprice_vwap_v130000.0"
    - "std_trend_ws100_midprice_vwap_v130000.0"
    - "vol_ws100_midprice_vwap_v130000.0"
    - "mean_trend_ws500_midprice_vwap_v130000.0"
    - "std_trend_ws500_midprice_vwap_v130000.0"
    - "vol_ws500_midprice_vwap_v130000.0"
    - "mean_trend_ws100_midprice_vwap_v220000.0"
    - "std_trend_ws100_midprice_vwap_v220000.0"
    - "vol_ws100_midprice_vwap_v220000.0"
    - "mean_trend_ws500_midprice_vwap_v220000.0"
    - "std_trend_ws500_midprice_vwap_v220000.0"
    - "vol_ws500_midprice_vwap_v220000.0"
    - "new_trend_value_ws100_midprice"
    - "new_trend_value_ws100_midprice_vwap_v130000.0"
    - "new_trend_value_ws100_midprice_vwap_v220000.0"
    - "new_trend_value_ws500_midprice"
    - "new_trend_value_ws500_midprice_vwap_v130000.0"
    - "new_trend_value_ws500_midprice_vwap_v220000.0"
    - "mean_trend_ws2500_midprice_vwap_v130000.0"
    - "mean_trend_ws2500_midprice_vwap_v220000.0"
    - "std_trend_ws2500_midprice_vwap_v220000.0"
    - "vol_ws2500_midprice_vwap_v220000.0"



