#--------------general settings-----------------
path_df: ../data/ETHUSD_VTE_ba_16:28-11.csv
train_start_idx: 1
train_end_idx:   10000000000
save_every:      10
n_experiments:   600
init_train_len:  25000
train_len:       1000
test_num:        200
test_len:        2000
test_step:       5

#--------------model settings-----------------
actions:
    - 0.05
    - 0.2
    - 1.0
layers:
    - 256
    - 32
    - 8

#--------------training settings-----------------
#---episodes and replay buffer
max_episode_len: 2
replay_memory_len: 64
replay_batch: 32
eval_every: 100
#---EvE variables
eps_start:     0.90
eps_end:       0.05
eps_decay:     500000
#---reward variables
reward_decay:  0.3
reg_vol:       40.0
warm_up_episodes: 100
#--- Q calculation: Qp + alpha * (R + gamma * Qt' - Qp)
alpha:         0.9
gamma:         0.5
#---learning rate
lr:            7e-5
lr_decay:      0.99
gradient_clip: 1e-1
#---target update settings
merge_dqns_every: 10  # not important if merge_soft == True
merge_soft: true
merge_alpha: 0.3

#--------------env settings-----------------
commission: -0.0002    
trading_step: 200      # how far we predict
window_step: 10
exclude_cols:
    - "target"


