#--------------general settings-----------------
path_df: /home/ugrek/Maquette/data/TEST_features.csv
eval_save_path_pref:  /media/ugrek/Backup/rl-finance/dqn_alpha/
train_start_idx: 5000
train_end_idx:   4500000
test_start_idx:  3500000
test_end_idx:    5150000
save_every:      2000
type:            dqn

#--------------model settings-----------------
# in BPs!
mode: spread
actions:
    - 5
    - 30
    - 200
layers: 
    - 1024
    - 256
    - 128


#--------------training settings-----------------
#---episodes and replay buffer
episodes:          2000
eval_every:        4000
max_episode_len:   100
replay_memory_len: 1024
replay_batch:      64
#---EvE variables
eps_start:         0.90
eps_end:           0.05
eps_decay:         500000
#---reward variables
reward_decay:      0.3
reg_vol:           5.0
warm_up_episodes: 1000
#--- Q calculation: Qp + alpha * (R + gamma * Qt' - Qp)
alpha:         0.5
gamma:         0.7
#---learning rate
lr:            1e-5
lr_decay:      0.9999
gradient_clip: 1e-7
#---target update settings
merge_dqns_every: 10  # not important if merge_soft == True
merge_soft:       true
merge_alpha:      0.6

#--------------env settings-----------------
need_to_scale:       true
trading_step:     300      # how far we predict
window_step:      299
commission:      -0.0002    
exclude_cols:
    - "mu"
    - "theta"



