#--------------general settings-----------------
path_df: /home/ugrek/Maquette/data/diploma/BTCUSDT_features_16384.csv
eval_save_path_pref:  /media/ugrek/Backup/rl-finance/dqn_ou_alpha/
train_start_idx: 5000
train_end_idx:   4000000
test_start_idx:  4200000
test_end_idx:    4400000
save_every:      1000
type:            dqn

#--------------model settings-----------------
# modes: spread, ou, as
mode:        ou
mr_out_k:    0.4
mr_in_k:     0.8
mr_crit_k:   5.0
mr_pos_vol:  1.0
mr_min_pr:   5 # in BPs!

mr_in_k_vars:
    -  0.0
    -  0.3
    - -0.3
    - -0.7
mr_out_k_vars:
    -  0.0
    -  0.4
    - -0.3
mr_crit_k_vars:
    -  0.0
    -  1.0
    - -3.0
layers: 
    - 1024
    - 256
    - 128

# currently relu, tanh are supported, see BateTypes
activation_f: tanh

#--------------training settings-----------------
#---episodes and replay buffer
episodes:           2000
eval_every:         4000
max_episode_len:    200
replay_memory_len:  2048
replay_batch:       128
#---EvE variables
eps_start:     0.70
eps_end:       0.05
eps_decay:     500000
#---reward variables
reward_decay:     0.6
reg_vol:          5.0
warm_up_episodes: 500
#--- Q calculation: Qp + alpha * (R + gamma * Qt' - Qp)
alpha:         0.3
gamma:         0.5
#---learning rate
lr:            1e-5
lr_decay:      0.9999
gradient_clip: 1e-2
#---target update settings
merge_dqns_every: 10  # not important if merge_soft == True
merge_soft: true
merge_alpha: 0.3

#--------------env settings-----------------
commission:   -0.0002    
trading_step:  100      # how far we predict
window_step:   99
need_to_scale: true
exclude_cols:
    - "mu"
    - "theta"


