#--------------general settings-----------------
path_df:              /home/ugrek/Maquette/data/TEST_features.csv
eval_save_path_pref:  /media/ugrek/Backup/rl-finance/td3_gr_alpha/
train_start_idx: 5000
train_end_idx:   4500000
test_start_idx:  4600000
test_end_idx:    4610000
save_every:      1000
type:            td3

#--------------model settings-----------------
mode:     grid
gr_delta:       0.003
gr_target_pr:   0.005
gr_max_qt:      13.0

A_layers: 
    - 256
    - 16
C_layers: 
    - 512
    - 16

# currently relu, tanh are supported, see BateTypes
activation_f: tanh

#--------------training settings-----------------
#---episodes and replay buffer
episodes:          1000
eval_every:        2000
max_episode_len:   100
replay_memory_len: 1024
replay_batch:      64
#---EvE variables
eps_start:     0.70
eps_end:       0.05
eps_decay:     70000
noise_sigma:   0.1
noise_mean:    0.0
#---reward variables
reg_vol:       10.0
reg_action:    1e-1
rew_offset:    5.0
warm_up_episodes: 500
reward_decay:  0.2
#--- Q calculation: Qp + alpha * (R + gamma * Qt' - Qp)
alpha:         0.2
gamma:         0.7
#---learning rate
lr_A:          1e-4
lr_C:          1e-7
lr_decay_A:    0.995
lr_decay_C:    0.993
gradient_clip: 1e-10
#---target update settings
t_beta:        0.6
reg_weights:   1e-5

#--------------env settings-----------------
need_to_scale: true
trading_step:  600
window_step:   599
commission:   -0.0002
exclude_cols:
    - "mu"
    - "theta"



