#--------------general settings-----------------
path_df:              /home/ugrek/Maquette/data/TEST_features.csv
eval_save_path_pref:  /media/ugrek/Backup/rl-finance/td3_ou_alpha/
train_start_idx: 5000
train_end_idx:   4500000
test_start_idx:  4600000
test_end_idx:    4610000
save_every:      1000
type:            td3

#--------------model settings-----------------
mode: ou
mr_out_k:    0.4
mr_in_k:     0.7
mr_crit_k:   5.0
mr_pos_vol:  1.0
mr_min_pr:   5 # in BPs!

A_layers: 
    - 256
    - 8
C_layers: 
    - 512
    - 32

#--------------training settings-----------------
#---episodes and replay buffer
episodes:          1000
eval_every:        2000
max_episode_len:   100
replay_memory_len: 1024
replay_batch:      64
#---EvE variables
eps_start:     0.70
eps_end:       0.05
eps_decay:     70000
noise_sigma:   0.1
noise_mean:    0.0
#---reward variables
reg_vol:       10.0
reg_action:    1e-1
rew_offset:    5.0
warm_up_episodes: 500
reward_decay:  0.2
#--- Q calculation: Qp + alpha * (R + gamma * Qt' - Qp)
alpha:         0.2
gamma:         0.7
#---learning rate
lr_A:          1e-5
lr_C:          1e-7
lr_decay_A:    0.995
lr_decay_C:    0.993
gradient_clip: 1e-7
#---target update settings
t_beta:        0.5
reg_weights:   1e-2

#--------------env settings-----------------
need_to_scale: true
trading_step:  100
window_step:   99
commission:   -0.0002
exclude_cols:
    - "mu"
    - "theta"




