#--------------general settings-----------------
path_df: ../data/ETHUSD_VTE_ba_16:28-11.csv
train_start_idx: 1
train_end_idx: 905000
test_start_idx: 910000
test_end_idx: end
save_every: 1000

#--------------model settings-----------------
A_layers: 
    - 128
C_layers: 
    - 128

#--------------training settings-----------------
#---episodes and replay buffer
episodes: 100000
eval_every: 100
max_episode_len: 3
replay_memory_len: 512
replay_batch: 64
#---EvE variables
eps_start:     0.90
eps_end:       0.05
eps_decay:     150000
noise_sigma:   0.05
noise_mean:    0.0
#---reward variables
reg_vol:       40.0
reg_action:    2e+1
reg_weights:   1e-2
rew_offset:    5.0
warm_up_episodes: 4000
reward_decay:  0.2
#--- Q calculation: Qp + alpha * (R + gamma * Qt' - Qp)
alpha:         0.9
gamma:         0.5
#---learning rate
lr_A:          1e-10
lr_C:          1e-4
lr_decay_A:    0.999
lr_decay_C:    0.999
gradient_clip: 1e-1
#---target update settings
t_beta:        0.2

#--------------env settings-----------------
trading_step: 200
window_step: 20
commission: -0.0002
exclude_cols:
    - "target"
    - "target_min"
    - "target_max" 
    - "midprice_vwap_v220000.0"
    - "vwap_midprice_diff_v220000.0"
    - "midprice_vwap_v130000.0"
    - "vwap_midprice_diff_v130000.0"
    - "log_vwap_midprice_ratio_v220000.0"
    - "nlrr_ws100"
    - "nlrr_ws500" 
    - "nlrr_ws2500" 
    - "mean_trend_ws100_midprice"
    - "std_trend_ws100_midprice"
    - "vol_ws100_midprice"
    - "mean_trend_ws500_midprice"
    - "std_trend_ws500_midprice"
    - "vol_ws500_midprice"
    - "mean_trend_ws100_midprice_vwap_v130000.0"
    - "std_trend_ws100_midprice_vwap_v130000.0"
    - "vol_ws100_midprice_vwap_v130000.0"
    - "mean_trend_ws500_midprice_vwap_v130000.0"
    - "std_trend_ws500_midprice_vwap_v130000.0"
    - "vol_ws500_midprice_vwap_v130000.0"
    - "mean_trend_ws100_midprice_vwap_v220000.0"
    - "std_trend_ws100_midprice_vwap_v220000.0"
    - "vol_ws100_midprice_vwap_v220000.0"
    - "mean_trend_ws500_midprice_vwap_v220000.0"
    - "std_trend_ws500_midprice_vwap_v220000.0"
    - "vol_ws500_midprice_vwap_v220000.0"
    - "new_trend_value_ws100_midprice"
    - "new_trend_value_ws100_midprice_vwap_v130000.0"
    - "new_trend_value_ws100_midprice_vwap_v220000.0"
    - "new_trend_value_ws500_midprice"
    - "new_trend_value_ws500_midprice_vwap_v130000.0"
    - "new_trend_value_ws500_midprice_vwap_v220000.0"
    - "mean_trend_ws2500_midprice_vwap_v130000.0"
    - "mean_trend_ws2500_midprice_vwap_v220000.0"
    - "std_trend_ws2500_midprice_vwap_v220000.0"
    - "vol_ws2500_midprice_vwap_v220000.0"
    - "scaled_std_trend_ws2500_midprice"
    - "scaled_vol_ws2500_midprice"
    - "scaled_new_trend_value_ws2500_midprice"
    - "scaled_new_trend_value_ws2500_midprice_vwap_v220000.0"



