#--------------general settings-----------------
path_df: /home/ugrek/Maquette/data/TEST_features.csv
train_start_idx: 1
train_end_idx: 3000000
test_start_idx: 3500000
test_end_idx: end
save_every: 1000

#--------------model settings-----------------
A_layers: 
    - 64
    - 8
C_layers: 
    - 128
    - 8

#--------------training settings-----------------
#---episodes and replay buffer
episodes: 100000
eval_every: 100
max_episode_len: 3
replay_memory_len: 512
replay_batch: 64
#---EvE variables
eps_start:     0.90
eps_end:       0.05
eps_decay:     50000
noise_sigma:   0.2
noise_mean:    0.0
#---reward variables
reg_vol:       30.0
reg_action:    1e+1
reg_weights:   1e-2
rew_offset:    5.0
warm_up_episodes: 50
reward_decay:  0.2
#--- Q calculation: Qp + alpha * (R + gamma * Qt' - Qp)
alpha:         0.9
gamma:         0.5
#---learning rate
lr_A:          1e-20
lr_C:          1e-5
lr_decay_A:    0.995
lr_decay_C:    0.999
gradient_clip: 1e-1
#---target update settings
t_beta:        0.3

#--------------env settings-----------------
trading_step: 200
window_step: 20
commission: -0.0002
exclude_cols:



